---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: cosmo
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(dplyr)
library(highcharter)

# read data
energy <- read_csv("all_energy_statistics.csv")
solar_energy <- energy %>% filter(category == "solar_electricity")
total_electricity <- energy %>% filter(category == "total_electricity")
```

```{r, include=FALSE}
top10_solar <- solar_energy %>% 
  group_by(country_or_area) %>% 
  summarise(total_quantity = sum(quantity, na.rm=T)) %>% 
  arrange(desc(total_quantity)) %>% 
  top_n(10)

top10_years <- solar_energy %>% 
  filter(country_or_area %in% setdiff(top10_solar$country_or_area, "China")) %>% 
  select(country_or_area, year, quantity) %>% 
  filter(year %in% 2000:2014) %>% 
  mutate(year = lubridate::ymd(year, truncated = 2L)) %>% 
  arrange(year)

italy <- top10_years %>%
  filter(country_or_area == "Italy")
italy <- xts::xts(italy$quantity, order.by = italy$year)

germany <- top10_years %>%
  filter(country_or_area == "Germany")
germany <- xts::xts(germany$quantity, order.by = germany$year)

usa <- top10_years %>%
  filter(country_or_area == "United States")
usa <- xts::xts(usa$quantity, order.by = usa$year)

grouped_totals <- energy %>% 
  group_by(country_or_area, category) %>% 
  summarise(total = sum(quantity, na.rm=T))

top_category <- grouped_totals %>% 
  group_by(country_or_area) %>% 
  arrange(desc(total)) %>% 
  top_n(1)

top_category <- top_category %>% 
  group_by(category) %>% 
  count()

top10_total_electricity <- total_electricity %>% 
  group_by(country_or_area) %>% 
  summarise(total_quantity = sum(quantity, na.rm=T)) %>% 
  arrange(desc(total_quantity)) %>% 
  top_n(10)

```


World Energy {data-orientation=rows data-icon="fa-bar-chart"}
=====================================

## Row 1 {data-height=110}

### Total Countries

```{r}
valueBox(length(unique(energy$country_or_area)), icon = "fa-ship", color="rgb(100,100,100)")
```
    
### Years range

```{r}
valueBox(paste0(min(energy$year), "-", max(energy$year)), icon = "fa-heart", color="rgb(200,100,100)")
```

### Total Quantity

```{r}
valueBox(paste0(round(sum(energy$quantity)/100000000), " per 100M"), icon = "fa-life-ring",color="rgb(26,110,204)")
```    

## Row 2 {data-height=500}

### Time Series Solar Production top 3 countries

```{r}
highchart(type = "stock") %>%
  hc_title(text = "") %>%
  hc_subtitle(text = "") %>%
  hc_add_series(italy) %>% 
  hc_add_series(germany) %>%
  hc_add_series(usa) %>%
  hc_add_theme(hc_theme_google())
```

## Row 3 {data-height=300}
   
### Top 10 Country Total Solar Production

```{r}
highchart() %>%
  hc_chart(type = "pie") %>%
  hc_add_series_labels_values(labels = as.factor(top10_solar$country_or_area), values = top10_solar$total_quantity) %>%
  hc_tooltip(pointFormat = paste('Total Quantity: {point.y}<br/><b>{point.percentage:.1f}%</b>')) %>%
  hc_title(text = "Top 10 Solar Energy Production") %>%
  hc_add_theme(hc_theme_google())
```   
    
    
### Top Category Count Worldwide

```{r}
highchart() %>%
  hc_chart(type = "pie") %>%
  hc_add_series_labels_values(labels = as.factor(top_category$category), values = top_category$n) %>%
  hc_tooltip(pointFormat = paste('Total Quantity: {point.y}<br/><b>{point.percentage:.1f}%</b>')) %>%
  hc_title(text = "Top Category count") %>%
  hc_add_theme(hc_theme_google())  

```   
    
        
### Top 10 by Total Electricity

```{r}
highchart() %>%
  hc_chart(type = "pie") %>%
  hc_add_series_labels_values(labels = as.factor(top10_total_electricity$country_or_area), values = top10_total_electricity$total_quantity) %>%
  hc_tooltip(pointFormat = paste('Total Quantity: {point.y}<br/><b>{point.percentage:.1f}%</b>')) %>%
  hc_title(text = "Top 10 Total Electricity Production") %>%
  hc_add_theme(hc_theme_google())
```
